### PR TITLE
FIX 701

### LINKED ISSUE #701: Multi-line settings aren't ignored properly by sync
🐛 **Describe the bug**  
When using the new per-platform sync feature, settings that run for more than one line aren't commented-out properly.

🌴 **Visual Studio Code Version :** Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850)
🌴 **Code Settings Sync Version :** 3.2.0
🌴 **Standard or Insiders :** Standard
🌴 **OSS or Portable :** neither?
🌴 **Operating System :** macOS Mojave 10.14.0
🌴 **Occurs On:** Download
🌴 **Proxy Enabled:** No

📰 **To Reproduce**

1. Have VS Code with sync set up on two different machines (can be the same OS, just use the `host` option instead of `os`), we'll call them Machine A and Machine B.
2. Create a user settings file on Machine A (in my case, Mac) like so:
```jsonc
{
  // @sync os=mac
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  }
}
```
3. Sync the settings file to Machine B (Windows for me)
4. This is what you'll end up with on Machine B:
```jsonc
{
  // @sync os=mac
  // "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  }
}
```

💪 **Expected behavior**
The setting should be properly commented-out on Machine B.

```jsonc
{
  // @sync os=mac
  // "editor.quickSuggestions": {
  //  "other": true,
  //  "comments": true,
  //  "strings": true
  // }
}
```

### PR DESCRIPTION
**Pull request by ioprotium**
#### Short description of what this resolves: Fix #701 

**Fixes**: #701

NOTE: This adds support for multi-line settings with code sync pragma. It only support one level of nested settings for now. 
Usage of pragmas in nested settings:
```javascript
  // @sync-ignore
  "setting.nested": {
    "key": "value"
  }

  // @sync os=linux
  "setting.nested2": [
     1,2,3
  ]
```

### CODE REVIEW

File: test/pragmaUtil/index.ts [hunk 1]
```diff
@@ -13,33 +13,12 @@ describe("Process before upload", function() {
     );
   });
 
-  it("should remove @sync-ignore and @sync ignore lines", () => {
```
Comment (shanalikhan) [inline test/pragmaUtil/index.ts]: may i know why these tests were removed.
also can you add test for multi settings

Comment (ioprotium) [reply test/pragmaUtil/index.ts]: It was removed since the new approach doesn't need separated methods to accomplish the same and some methods were removed. 
I added a new test for multi-line settings but I can't  run the test because TSLint throws errors in "commons.ts" file. Check the latest commits.

**Comment by ioprotium** [comment]
Cool! I'm finishing my latest tasks at my current job an then I will be
free for one or two weeks.
This weekend I will look some other issues to help with since I got
familiar with all the code sync code base.

Kind regards

**Comment by shanalikhan** [comment]
Thanks really nice!

Bounty is available for issues here : https://github.com/shanalikhan/code-settings-sync/labels/bounty

> I got familiar with all the code sync code base.

I would request you to look into this : #396 as its the one of the most important bug.
